"""empty message

Revision ID: 1ed2a01e6fb4
Revises: 284e41c5ab68
Create Date: 2022-07-31 13:58:54.040508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed2a01e6fb4'
down_revision = '284e41c5ab68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'facebook_link')
    # ### end Alembic commands ###
