"""empty message

Revision ID: 284e41c5ab68
Revises: 2c7eac9b983b
Create Date: 2022-07-30 20:05:21.702527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284e41c5ab68'
down_revision = '2c7eac9b983b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shows_id_key', 'shows', type_='unique')
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('shows_id_key', 'shows', ['id'])
    # ### end Alembic commands ###
