"""empty message

Revision ID: 2c7eac9b983b
Revises: 22503f2fff49
Create Date: 2022-07-30 20:01:56.183786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7eac9b983b'
down_revision = '22503f2fff49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shows', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='unique')
    # ### end Alembic commands ###
